paths:
  captions_file: "./Images/captions.txt"
  cleaned_captions_file: "./Images/cleaned_captions.txt"
  images_folder: "./Images/Images"
  model_save_dir: "saved_models/fine_tuned_blip"
  logs_dir: "logs"

model:
  base_model: "Salesforce/blip-image-captioning-large"

training:
  epochs: 1
  batch_size: 4
  learning_rate: 0.00005
  gradient_accumulation_steps: 4
  log_interval: 100
  max_samples: 6000

evaluation:
  batch_size: 4
